/// <reference types="vite/client" />

import Appsignal from "@appsignal/javascript";
import { plugin } from "@appsignal/plugin-window-events";

function initAppSignal() {
    let client: Appsignal | { sendError: (err: Error) => void } = {
        sendError: (_err: Error) => {},
    };

    function configure(apikey: string, version: string, isSsr: boolean) {
        client = new Appsignal({ key: apikey, revision: version });
        if (!isSsr) (client as Appsignal).use(plugin());
    }

    return {
        client,
        configure,
        sendError: client.sendError,
    };
}

export const appsignal = initAppSignal();

declare global {
    interface ImportMetaEnv {
        readonly VITE_APPSIGNAL_API_KEY: string;
    }

    interface ImportMeta {
        readonly env: ImportMetaEnv;
    }

    // this is generated by vite by reading package.json
    const __APP_VERSION__: string;
}
